apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-camunda-deployment
  labels:
    app: app1-camunda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1-camunda
  template:
    metadata:
      labels:
        app: app1-camunda
    spec:
      containers:
        - name: app1-camunda
          image: camunda/camunda-bpm-platform:latest
          ports:
            - containerPort: 8080
# To schedule pods on based on NodeSelectors
      nodeSelector:
        app: system-apps


   