apiVersion: v1
kind: Service
metadata:
  name: app1-camundat-clusterip-service
  labels:
    app: app1-camundat
spec:
  type: LoadBalancer
  selector:
    app: app1-camundat
  ports:
    - port: 8080
      targetPort: 8080
